//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 3.5.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// $ANTLR 3.5.2 Dsl.g 2019-08-21 20:50:43

// The variable 'variable' is assigned but its value is never used.
#pragma warning disable 219
// Unreachable code detected.
#pragma warning disable 162
// Missing XML comment for publicly visible type or member 'Type_or_Member'
#pragma warning disable 1591
// CLS compliance checking will not be performed on 'type' because it is not visible from outside this assembly.
#pragma warning disable 3019


using System.Collections.Generic;
using Antlr.Runtime;
using Antlr.Runtime.Misc;

namespace ParserTree.AntlrCode
{
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "3.5.2")]
[System.CLSCompliant(false)]
public partial class DslLexer : Antlr.Runtime.Lexer
{
	public const int EOF=-1;
	public const int T__32=32;
	public const int T__33=33;
	public const int AND_STATEMENT=4;
	public const int APOSTRAPHE=5;
	public const int COMMENT=6;
	public const int DIGIT=7;
	public const int EQUAL=8;
	public const int GREATER=9;
	public const int GREATER_THAN=10;
	public const int GREATER_THAN_EQUAL=11;
	public const int INT=12;
	public const int IS=13;
	public const int LESS=14;
	public const int LESS_THAN=15;
	public const int LESS_THAN_EQUAL=16;
	public const int LETTER=17;
	public const int LINE_COMMENT_SLASH=18;
	public const int NEWLINE=19;
	public const int NOT=20;
	public const int NOT_EQUAL=21;
	public const int OR_STATEMENT=22;
	public const int PLUS=23;
	public const int PROGRAM=24;
	public const int STAR=25;
	public const int STRING_LITERAL=26;
	public const int THAN=27;
	public const int VARIABLE=28;
	public const int WHEN=29;
	public const int WHEN_STATEMENT=30;
	public const int WS=31;

	// delegates
	// delegators

	public DslLexer()
	{
		OnCreated();
	}

	public DslLexer(ICharStream input )
		: this(input, new RecognizerSharedState())
	{
	}

	public DslLexer(ICharStream input, RecognizerSharedState state)
		: base(input, state)
	{

		OnCreated();
	}
	public override string GrammarFileName { get { return "Dsl.g"; } }


	partial void OnCreated();
	partial void EnterRule(string ruleName, int ruleIndex);
	partial void LeaveRule(string ruleName, int ruleIndex);

	partial void EnterRule_T__32();
	partial void LeaveRule_T__32();

	// $ANTLR start "T__32"
	[GrammarRule("T__32")]
	private void mT__32()
	{
		EnterRule_T__32();
		EnterRule("T__32", 1);
		TraceIn("T__32", 1);
		try
		{
			int _type = T__32;
			int _channel = DefaultTokenChannel;
			// Dsl.g:10:7: ( '[' )
			DebugEnterAlt(1);
			// Dsl.g:10:9: '['
			{
			DebugLocation(10, 9);
			Match('['); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__32", 1);
			LeaveRule("T__32", 1);
			LeaveRule_T__32();
		}
	}
	// $ANTLR end "T__32"

	partial void EnterRule_T__33();
	partial void LeaveRule_T__33();

	// $ANTLR start "T__33"
	[GrammarRule("T__33")]
	private void mT__33()
	{
		EnterRule_T__33();
		EnterRule("T__33", 2);
		TraceIn("T__33", 2);
		try
		{
			int _type = T__33;
			int _channel = DefaultTokenChannel;
			// Dsl.g:11:7: ( ']' )
			DebugEnterAlt(1);
			// Dsl.g:11:9: ']'
			{
			DebugLocation(11, 9);
			Match(']'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__33", 2);
			LeaveRule("T__33", 2);
			LeaveRule_T__33();
		}
	}
	// $ANTLR end "T__33"

	partial void EnterRule_APOSTRAPHE();
	partial void LeaveRule_APOSTRAPHE();

	// $ANTLR start "APOSTRAPHE"
	[GrammarRule("APOSTRAPHE")]
	private void mAPOSTRAPHE()
	{
		EnterRule_APOSTRAPHE();
		EnterRule("APOSTRAPHE", 3);
		TraceIn("APOSTRAPHE", 3);
		try
		{
			int _type = APOSTRAPHE;
			int _channel = DefaultTokenChannel;
			// Dsl.g:57:12: ( '\\'' )
			DebugEnterAlt(1);
			// Dsl.g:57:14: '\\''
			{
			DebugLocation(57, 14);
			Match('\''); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("APOSTRAPHE", 3);
			LeaveRule("APOSTRAPHE", 3);
			LeaveRule_APOSTRAPHE();
		}
	}
	// $ANTLR end "APOSTRAPHE"

	partial void EnterRule_STAR();
	partial void LeaveRule_STAR();

	// $ANTLR start "STAR"
	[GrammarRule("STAR")]
	private void mSTAR()
	{
		EnterRule_STAR();
		EnterRule("STAR", 4);
		TraceIn("STAR", 4);
		try
		{
			int _type = STAR;
			int _channel = DefaultTokenChannel;
			// Dsl.g:58:5: ( '*' )
			DebugEnterAlt(1);
			// Dsl.g:58:7: '*'
			{
			DebugLocation(58, 7);
			Match('*'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("STAR", 4);
			LeaveRule("STAR", 4);
			LeaveRule_STAR();
		}
	}
	// $ANTLR end "STAR"

	partial void EnterRule_PLUS();
	partial void LeaveRule_PLUS();

	// $ANTLR start "PLUS"
	[GrammarRule("PLUS")]
	private void mPLUS()
	{
		EnterRule_PLUS();
		EnterRule("PLUS", 5);
		TraceIn("PLUS", 5);
		try
		{
			int _type = PLUS;
			int _channel = DefaultTokenChannel;
			// Dsl.g:59:5: ( '+' )
			DebugEnterAlt(1);
			// Dsl.g:59:7: '+'
			{
			DebugLocation(59, 7);
			Match('+'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("PLUS", 5);
			LeaveRule("PLUS", 5);
			LeaveRule_PLUS();
		}
	}
	// $ANTLR end "PLUS"

	partial void EnterRule_EQUAL();
	partial void LeaveRule_EQUAL();

	// $ANTLR start "EQUAL"
	[GrammarRule("EQUAL")]
	private void mEQUAL()
	{
		EnterRule_EQUAL();
		EnterRule("EQUAL", 6);
		TraceIn("EQUAL", 6);
		try
		{
			int _type = EQUAL;
			int _channel = DefaultTokenChannel;
			// Dsl.g:60:6: ( 'equal' )
			DebugEnterAlt(1);
			// Dsl.g:60:8: 'equal'
			{
			DebugLocation(60, 8);
			Match("equal"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("EQUAL", 6);
			LeaveRule("EQUAL", 6);
			LeaveRule_EQUAL();
		}
	}
	// $ANTLR end "EQUAL"

	partial void EnterRule_GREATER();
	partial void LeaveRule_GREATER();

	// $ANTLR start "GREATER"
	[GrammarRule("GREATER")]
	private void mGREATER()
	{
		EnterRule_GREATER();
		EnterRule("GREATER", 7);
		TraceIn("GREATER", 7);
		try
		{
			int _type = GREATER;
			int _channel = DefaultTokenChannel;
			// Dsl.g:61:8: ( 'greater' )
			DebugEnterAlt(1);
			// Dsl.g:61:10: 'greater'
			{
			DebugLocation(61, 10);
			Match("greater"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("GREATER", 7);
			LeaveRule("GREATER", 7);
			LeaveRule_GREATER();
		}
	}
	// $ANTLR end "GREATER"

	partial void EnterRule_LESS();
	partial void LeaveRule_LESS();

	// $ANTLR start "LESS"
	[GrammarRule("LESS")]
	private void mLESS()
	{
		EnterRule_LESS();
		EnterRule("LESS", 8);
		TraceIn("LESS", 8);
		try
		{
			int _type = LESS;
			int _channel = DefaultTokenChannel;
			// Dsl.g:62:5: ( 'less' )
			DebugEnterAlt(1);
			// Dsl.g:62:7: 'less'
			{
			DebugLocation(62, 7);
			Match("less"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("LESS", 8);
			LeaveRule("LESS", 8);
			LeaveRule_LESS();
		}
	}
	// $ANTLR end "LESS"

	partial void EnterRule_THAN();
	partial void LeaveRule_THAN();

	// $ANTLR start "THAN"
	[GrammarRule("THAN")]
	private void mTHAN()
	{
		EnterRule_THAN();
		EnterRule("THAN", 9);
		TraceIn("THAN", 9);
		try
		{
			int _type = THAN;
			int _channel = DefaultTokenChannel;
			// Dsl.g:63:5: ( 'than' )
			DebugEnterAlt(1);
			// Dsl.g:63:7: 'than'
			{
			DebugLocation(63, 7);
			Match("than"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("THAN", 9);
			LeaveRule("THAN", 9);
			LeaveRule_THAN();
		}
	}
	// $ANTLR end "THAN"

	partial void EnterRule_NOT();
	partial void LeaveRule_NOT();

	// $ANTLR start "NOT"
	[GrammarRule("NOT")]
	private void mNOT()
	{
		EnterRule_NOT();
		EnterRule("NOT", 10);
		TraceIn("NOT", 10);
		try
		{
			int _type = NOT;
			int _channel = DefaultTokenChannel;
			// Dsl.g:64:4: ( 'not' )
			DebugEnterAlt(1);
			// Dsl.g:64:6: 'not'
			{
			DebugLocation(64, 6);
			Match("not"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("NOT", 10);
			LeaveRule("NOT", 10);
			LeaveRule_NOT();
		}
	}
	// $ANTLR end "NOT"

	partial void EnterRule_IS();
	partial void LeaveRule_IS();

	// $ANTLR start "IS"
	[GrammarRule("IS")]
	private void mIS()
	{
		EnterRule_IS();
		EnterRule("IS", 11);
		TraceIn("IS", 11);
		try
		{
			int _type = IS;
			int _channel = DefaultTokenChannel;
			// Dsl.g:65:3: ( 'is' )
			DebugEnterAlt(1);
			// Dsl.g:65:5: 'is'
			{
			DebugLocation(65, 5);
			Match("is"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("IS", 11);
			LeaveRule("IS", 11);
			LeaveRule_IS();
		}
	}
	// $ANTLR end "IS"

	partial void EnterRule_WHEN();
	partial void LeaveRule_WHEN();

	// $ANTLR start "WHEN"
	[GrammarRule("WHEN")]
	private void mWHEN()
	{
		EnterRule_WHEN();
		EnterRule("WHEN", 12);
		TraceIn("WHEN", 12);
		try
		{
			int _type = WHEN;
			int _channel = DefaultTokenChannel;
			// Dsl.g:66:5: ( 'when' )
			DebugEnterAlt(1);
			// Dsl.g:66:7: 'when'
			{
			DebugLocation(66, 7);
			Match("when"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("WHEN", 12);
			LeaveRule("WHEN", 12);
			LeaveRule_WHEN();
		}
	}
	// $ANTLR end "WHEN"

	partial void EnterRule_VARIABLE();
	partial void LeaveRule_VARIABLE();

	// $ANTLR start "VARIABLE"
	[GrammarRule("VARIABLE")]
	private void mVARIABLE()
	{
		EnterRule_VARIABLE();
		EnterRule("VARIABLE", 13);
		TraceIn("VARIABLE", 13);
		try
		{
			int _type = VARIABLE;
			int _channel = DefaultTokenChannel;
			// Dsl.g:67:9: ( ( LETTER )+ )
			DebugEnterAlt(1);
			// Dsl.g:67:11: ( LETTER )+
			{
			DebugLocation(67, 11);
			// Dsl.g:67:11: ( LETTER )+
			int cnt1=0;
			try { DebugEnterSubRule(1);
			while (true)
			{
				int alt1=2;
				try { DebugEnterDecision(1, false);
				int LA1_1 = input.LA(1);

				if (((LA1_1>='A' && LA1_1<='Z')||(LA1_1>='a' && LA1_1<='z')))
				{
					alt1 = 1;
				}


				} finally { DebugExitDecision(1); }
				switch (alt1)
				{
				case 1:
					DebugEnterAlt(1);
					// Dsl.g:
					{
					DebugLocation(67, 11);
					input.Consume();


					}
					break;

				default:
					if (cnt1 >= 1)
						goto loop1;

					EarlyExitException eee1 = new EarlyExitException( 1, input );
					DebugRecognitionException(eee1);
					throw eee1;
				}
				cnt1++;
			}
			loop1:
				;

			} finally { DebugExitSubRule(1); }


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("VARIABLE", 13);
			LeaveRule("VARIABLE", 13);
			LeaveRule_VARIABLE();
		}
	}
	// $ANTLR end "VARIABLE"

	partial void EnterRule_NEWLINE();
	partial void LeaveRule_NEWLINE();

	// $ANTLR start "NEWLINE"
	[GrammarRule("NEWLINE")]
	private void mNEWLINE()
	{
		EnterRule_NEWLINE();
		EnterRule("NEWLINE", 14);
		TraceIn("NEWLINE", 14);
		try
		{
			int _type = NEWLINE;
			int _channel = DefaultTokenChannel;
			// Dsl.g:68:8: ( ( '\\n' | '\\r' ) )
			DebugEnterAlt(1);
			// Dsl.g:
			{
			DebugLocation(68, 8);
			if (input.LA(1)=='\n'||input.LA(1)=='\r')
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("NEWLINE", 14);
			LeaveRule("NEWLINE", 14);
			LeaveRule_NEWLINE();
		}
	}
	// $ANTLR end "NEWLINE"

	partial void EnterRule_STRING_LITERAL();
	partial void LeaveRule_STRING_LITERAL();

	// $ANTLR start "STRING_LITERAL"
	[GrammarRule("STRING_LITERAL")]
	private void mSTRING_LITERAL()
	{
		EnterRule_STRING_LITERAL();
		EnterRule("STRING_LITERAL", 15);
		TraceIn("STRING_LITERAL", 15);
		try
		{
			int _type = STRING_LITERAL;
			int _channel = DefaultTokenChannel;
			// Dsl.g:69:15: ( APOSTRAPHE (~ ( APOSTRAPHE ) )* APOSTRAPHE )
			DebugEnterAlt(1);
			// Dsl.g:69:17: APOSTRAPHE (~ ( APOSTRAPHE ) )* APOSTRAPHE
			{
			DebugLocation(69, 17);
			mAPOSTRAPHE(); 
			DebugLocation(69, 28);
			// Dsl.g:69:28: (~ ( APOSTRAPHE ) )*
			try { DebugEnterSubRule(2);
			while (true)
			{
				int alt2=2;
				try { DebugEnterDecision(2, false);
				int LA2_1 = input.LA(1);

				if (((LA2_1>='\u0000' && LA2_1<='&')||(LA2_1>='(' && LA2_1<='\uFFFF')))
				{
					alt2 = 1;
				}


				} finally { DebugExitDecision(2); }
				switch ( alt2 )
				{
				case 1:
					DebugEnterAlt(1);
					// Dsl.g:
					{
					DebugLocation(69, 28);
					input.Consume();


					}
					break;

				default:
					goto loop2;
				}
			}

			loop2:
				;

			} finally { DebugExitSubRule(2); }

			DebugLocation(69, 43);
			mAPOSTRAPHE(); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("STRING_LITERAL", 15);
			LeaveRule("STRING_LITERAL", 15);
			LeaveRule_STRING_LITERAL();
		}
	}
	// $ANTLR end "STRING_LITERAL"

	partial void EnterRule_INT();
	partial void LeaveRule_INT();

	// $ANTLR start "INT"
	[GrammarRule("INT")]
	private void mINT()
	{
		EnterRule_INT();
		EnterRule("INT", 16);
		TraceIn("INT", 16);
		try
		{
			int _type = INT;
			int _channel = DefaultTokenChannel;
			// Dsl.g:70:5: ( ( DIGIT )+ )
			DebugEnterAlt(1);
			// Dsl.g:70:7: ( DIGIT )+
			{
			DebugLocation(70, 7);
			// Dsl.g:70:7: ( DIGIT )+
			int cnt3=0;
			try { DebugEnterSubRule(3);
			while (true)
			{
				int alt3=2;
				try { DebugEnterDecision(3, false);
				int LA3_1 = input.LA(1);

				if (((LA3_1>='0' && LA3_1<='9')))
				{
					alt3 = 1;
				}


				} finally { DebugExitDecision(3); }
				switch (alt3)
				{
				case 1:
					DebugEnterAlt(1);
					// Dsl.g:
					{
					DebugLocation(70, 7);
					input.Consume();


					}
					break;

				default:
					if (cnt3 >= 1)
						goto loop3;

					EarlyExitException eee3 = new EarlyExitException( 3, input );
					DebugRecognitionException(eee3);
					throw eee3;
				}
				cnt3++;
			}
			loop3:
				;

			} finally { DebugExitSubRule(3); }


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("INT", 16);
			LeaveRule("INT", 16);
			LeaveRule_INT();
		}
	}
	// $ANTLR end "INT"

	partial void EnterRule_LETTER();
	partial void LeaveRule_LETTER();

	// $ANTLR start "LETTER"
	[GrammarRule("LETTER")]
	private void mLETTER()
	{
		EnterRule_LETTER();
		EnterRule("LETTER", 17);
		TraceIn("LETTER", 17);
		try
		{
			// Dsl.g:71:17: ( ( 'a' .. 'z' | 'A' .. 'Z' ) )
			DebugEnterAlt(1);
			// Dsl.g:
			{
			DebugLocation(71, 17);
			if ((input.LA(1)>='A' && input.LA(1)<='Z')||(input.LA(1)>='a' && input.LA(1)<='z'))
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

		}
		finally
		{
			TraceOut("LETTER", 17);
			LeaveRule("LETTER", 17);
			LeaveRule_LETTER();
		}
	}
	// $ANTLR end "LETTER"

	partial void EnterRule_DIGIT();
	partial void LeaveRule_DIGIT();

	// $ANTLR start "DIGIT"
	[GrammarRule("DIGIT")]
	private void mDIGIT()
	{
		EnterRule_DIGIT();
		EnterRule("DIGIT", 18);
		TraceIn("DIGIT", 18);
		try
		{
			// Dsl.g:72:15: ( '0' .. '9' )
			DebugEnterAlt(1);
			// Dsl.g:
			{
			DebugLocation(72, 15);
			if ((input.LA(1)>='0' && input.LA(1)<='9'))
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

		}
		finally
		{
			TraceOut("DIGIT", 18);
			LeaveRule("DIGIT", 18);
			LeaveRule_DIGIT();
		}
	}
	// $ANTLR end "DIGIT"

	partial void EnterRule_WS();
	partial void LeaveRule_WS();

	// $ANTLR start "WS"
	[GrammarRule("WS")]
	private void mWS()
	{
		EnterRule_WS();
		EnterRule("WS", 19);
		TraceIn("WS", 19);
		try
		{
			int _type = WS;
			int _channel = DefaultTokenChannel;
			// Dsl.g:73:4: ( ( ' ' | '\\t' )+ )
			DebugEnterAlt(1);
			// Dsl.g:73:7: ( ' ' | '\\t' )+
			{
			DebugLocation(73, 7);
			// Dsl.g:73:7: ( ' ' | '\\t' )+
			int cnt4=0;
			try { DebugEnterSubRule(4);
			while (true)
			{
				int alt4=2;
				try { DebugEnterDecision(4, false);
				int LA4_1 = input.LA(1);

				if ((LA4_1=='\t'||LA4_1==' '))
				{
					alt4 = 1;
				}


				} finally { DebugExitDecision(4); }
				switch (alt4)
				{
				case 1:
					DebugEnterAlt(1);
					// Dsl.g:
					{
					DebugLocation(73, 7);
					input.Consume();


					}
					break;

				default:
					if (cnt4 >= 1)
						goto loop4;

					EarlyExitException eee4 = new EarlyExitException( 4, input );
					DebugRecognitionException(eee4);
					throw eee4;
				}
				cnt4++;
			}
			loop4:
				;

			} finally { DebugExitSubRule(4); }

			DebugLocation(73, 19);
			_channel = Hidden;

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("WS", 19);
			LeaveRule("WS", 19);
			LeaveRule_WS();
		}
	}
	// $ANTLR end "WS"

	partial void EnterRule_COMMENT();
	partial void LeaveRule_COMMENT();

	// $ANTLR start "COMMENT"
	[GrammarRule("COMMENT")]
	private void mCOMMENT()
	{
		EnterRule_COMMENT();
		EnterRule("COMMENT", 20);
		TraceIn("COMMENT", 20);
		try
		{
			int _type = COMMENT;
			int _channel = DefaultTokenChannel;
			// Dsl.g:74:9: ( '/*' ( . )* '*/' )
			DebugEnterAlt(1);
			// Dsl.g:74:11: '/*' ( . )* '*/'
			{
			DebugLocation(74, 11);
			Match("/*"); 

			DebugLocation(74, 16);
			// Dsl.g:74:16: ( . )*
			try { DebugEnterSubRule(5);
			while (true)
			{
				int alt5=2;
				try { DebugEnterDecision(5, false);
				int LA5_1 = input.LA(1);

				if ((LA5_1=='*'))
				{
					int LA5_2 = input.LA(2);

					if ((LA5_2=='/'))
					{
						alt5 = 2;
					}
					else if (((LA5_2>='\u0000' && LA5_2<='.')||(LA5_2>='0' && LA5_2<='\uFFFF')))
					{
						alt5 = 1;
					}


				}
				else if (((LA5_1>='\u0000' && LA5_1<=')')||(LA5_1>='+' && LA5_1<='\uFFFF')))
				{
					alt5 = 1;
				}


				} finally { DebugExitDecision(5); }
				switch ( alt5 )
				{
				case 1:
					DebugEnterAlt(1);
					// Dsl.g:74:16: .
					{
					DebugLocation(74, 16);
					MatchAny(); 

					}
					break;

				default:
					goto loop5;
				}
			}

			loop5:
				;

			} finally { DebugExitSubRule(5); }

			DebugLocation(74, 19);
			Match("*/"); 

			DebugLocation(74, 24);
			_channel = Hidden;

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("COMMENT", 20);
			LeaveRule("COMMENT", 20);
			LeaveRule_COMMENT();
		}
	}
	// $ANTLR end "COMMENT"

	partial void EnterRule_LINE_COMMENT_SLASH();
	partial void LeaveRule_LINE_COMMENT_SLASH();

	// $ANTLR start "LINE_COMMENT_SLASH"
	[GrammarRule("LINE_COMMENT_SLASH")]
	private void mLINE_COMMENT_SLASH()
	{
		EnterRule_LINE_COMMENT_SLASH();
		EnterRule("LINE_COMMENT_SLASH", 21);
		TraceIn("LINE_COMMENT_SLASH", 21);
		try
		{
			int _type = LINE_COMMENT_SLASH;
			int _channel = DefaultTokenChannel;
			// Dsl.g:75:20: ( '//' (~ NEWLINE )* )
			DebugEnterAlt(1);
			// Dsl.g:75:22: '//' (~ NEWLINE )*
			{
			DebugLocation(75, 22);
			Match("//"); 

			DebugLocation(75, 27);
			// Dsl.g:75:27: (~ NEWLINE )*
			try { DebugEnterSubRule(6);
			while (true)
			{
				int alt6=2;
				try { DebugEnterDecision(6, false);
				int LA6_1 = input.LA(1);

				if (((LA6_1>='\u0000' && LA6_1<='\t')||(LA6_1>='\u000B' && LA6_1<='\f')||(LA6_1>='\u000E' && LA6_1<='\uFFFF')))
				{
					alt6 = 1;
				}


				} finally { DebugExitDecision(6); }
				switch ( alt6 )
				{
				case 1:
					DebugEnterAlt(1);
					// Dsl.g:
					{
					DebugLocation(75, 27);
					input.Consume();


					}
					break;

				default:
					goto loop6;
				}
			}

			loop6:
				;

			} finally { DebugExitSubRule(6); }

			DebugLocation(75, 37);
			_channel = Hidden;

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("LINE_COMMENT_SLASH", 21);
			LeaveRule("LINE_COMMENT_SLASH", 21);
			LeaveRule_LINE_COMMENT_SLASH();
		}
	}
	// $ANTLR end "LINE_COMMENT_SLASH"

	public override void mTokens()
	{
		// Dsl.g:1:8: ( T__32 | T__33 | APOSTRAPHE | STAR | PLUS | EQUAL | GREATER | LESS | THAN | NOT | IS | WHEN | VARIABLE | NEWLINE | STRING_LITERAL | INT | WS | COMMENT | LINE_COMMENT_SLASH )
		int alt7=19;
		try { DebugEnterDecision(7, false);
		switch (input.LA(1))
		{
		case '[':
			{
			alt7 = 1;
			}
			break;
		case ']':
			{
			alt7 = 2;
			}
			break;
		case '\'':
			{
			int LA7_2 = input.LA(2);

			if (((LA7_2>='\u0000' && LA7_2<='\uFFFF')))
			{
				alt7 = 15;
			}
			else
			{
				alt7 = 3;
			}
			}
			break;
		case '*':
			{
			alt7 = 4;
			}
			break;
		case '+':
			{
			alt7 = 5;
			}
			break;
		case 'e':
			{
			int LA7_2 = input.LA(2);

			if ((LA7_2=='q'))
			{
				int LA7_3 = input.LA(3);

				if ((LA7_3=='u'))
				{
					int LA7_4 = input.LA(4);

					if ((LA7_4=='a'))
					{
						int LA7_5 = input.LA(5);

						if ((LA7_5=='l'))
						{
							int LA7_6 = input.LA(6);

							if (((LA7_6>='A' && LA7_6<='Z')||(LA7_6>='a' && LA7_6<='z')))
							{
								alt7 = 13;
							}
							else
							{
								alt7 = 6;
							}
						}
						else
						{
							alt7 = 13;
						}
					}
					else
					{
						alt7 = 13;
					}
				}
				else
				{
					alt7 = 13;
				}
			}
			else
			{
				alt7 = 13;
			}
			}
			break;
		case 'g':
			{
			int LA7_2 = input.LA(2);

			if ((LA7_2=='r'))
			{
				int LA7_3 = input.LA(3);

				if ((LA7_3=='e'))
				{
					int LA7_4 = input.LA(4);

					if ((LA7_4=='a'))
					{
						int LA7_5 = input.LA(5);

						if ((LA7_5=='t'))
						{
							int LA7_6 = input.LA(6);

							if ((LA7_6=='e'))
							{
								int LA7_7 = input.LA(7);

								if ((LA7_7=='r'))
								{
									int LA7_8 = input.LA(8);

									if (((LA7_8>='A' && LA7_8<='Z')||(LA7_8>='a' && LA7_8<='z')))
									{
										alt7 = 13;
									}
									else
									{
										alt7 = 7;
									}
								}
								else
								{
									alt7 = 13;
								}
							}
							else
							{
								alt7 = 13;
							}
						}
						else
						{
							alt7 = 13;
						}
					}
					else
					{
						alt7 = 13;
					}
				}
				else
				{
					alt7 = 13;
				}
			}
			else
			{
				alt7 = 13;
			}
			}
			break;
		case 'l':
			{
			int LA7_2 = input.LA(2);

			if ((LA7_2=='e'))
			{
				int LA7_3 = input.LA(3);

				if ((LA7_3=='s'))
				{
					int LA7_4 = input.LA(4);

					if ((LA7_4=='s'))
					{
						int LA7_5 = input.LA(5);

						if (((LA7_5>='A' && LA7_5<='Z')||(LA7_5>='a' && LA7_5<='z')))
						{
							alt7 = 13;
						}
						else
						{
							alt7 = 8;
						}
					}
					else
					{
						alt7 = 13;
					}
				}
				else
				{
					alt7 = 13;
				}
			}
			else
			{
				alt7 = 13;
			}
			}
			break;
		case 't':
			{
			int LA7_2 = input.LA(2);

			if ((LA7_2=='h'))
			{
				int LA7_3 = input.LA(3);

				if ((LA7_3=='a'))
				{
					int LA7_4 = input.LA(4);

					if ((LA7_4=='n'))
					{
						int LA7_5 = input.LA(5);

						if (((LA7_5>='A' && LA7_5<='Z')||(LA7_5>='a' && LA7_5<='z')))
						{
							alt7 = 13;
						}
						else
						{
							alt7 = 9;
						}
					}
					else
					{
						alt7 = 13;
					}
				}
				else
				{
					alt7 = 13;
				}
			}
			else
			{
				alt7 = 13;
			}
			}
			break;
		case 'n':
			{
			int LA7_2 = input.LA(2);

			if ((LA7_2=='o'))
			{
				int LA7_3 = input.LA(3);

				if ((LA7_3=='t'))
				{
					int LA7_4 = input.LA(4);

					if (((LA7_4>='A' && LA7_4<='Z')||(LA7_4>='a' && LA7_4<='z')))
					{
						alt7 = 13;
					}
					else
					{
						alt7 = 10;
					}
				}
				else
				{
					alt7 = 13;
				}
			}
			else
			{
				alt7 = 13;
			}
			}
			break;
		case 'i':
			{
			int LA7_2 = input.LA(2);

			if ((LA7_2=='s'))
			{
				int LA7_3 = input.LA(3);

				if (((LA7_3>='A' && LA7_3<='Z')||(LA7_3>='a' && LA7_3<='z')))
				{
					alt7 = 13;
				}
				else
				{
					alt7 = 11;
				}
			}
			else
			{
				alt7 = 13;
			}
			}
			break;
		case 'w':
			{
			int LA7_2 = input.LA(2);

			if ((LA7_2=='h'))
			{
				int LA7_3 = input.LA(3);

				if ((LA7_3=='e'))
				{
					int LA7_4 = input.LA(4);

					if ((LA7_4=='n'))
					{
						int LA7_5 = input.LA(5);

						if (((LA7_5>='A' && LA7_5<='Z')||(LA7_5>='a' && LA7_5<='z')))
						{
							alt7 = 13;
						}
						else
						{
							alt7 = 12;
						}
					}
					else
					{
						alt7 = 13;
					}
				}
				else
				{
					alt7 = 13;
				}
			}
			else
			{
				alt7 = 13;
			}
			}
			break;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'f':
		case 'h':
		case 'j':
		case 'k':
		case 'm':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 'u':
		case 'v':
		case 'x':
		case 'y':
		case 'z':
			{
			alt7 = 13;
			}
			break;
		case '\n':
		case '\r':
			{
			alt7 = 14;
			}
			break;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
			{
			alt7 = 16;
			}
			break;
		case '\t':
		case ' ':
			{
			alt7 = 17;
			}
			break;
		case '/':
			{
			int LA7_2 = input.LA(2);

			if ((LA7_2=='*'))
			{
				alt7 = 18;
			}
			else if ((LA7_2=='/'))
			{
				alt7 = 19;
			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 7, 17, input, 2);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			}
			break;
		default:
			{
				NoViableAltException nvae = new NoViableAltException("", 7, 0, input, 1);
				DebugRecognitionException(nvae);
				throw nvae;
			}
		}

		} finally { DebugExitDecision(7); }
		switch (alt7)
		{
		case 1:
			DebugEnterAlt(1);
			// Dsl.g:1:10: T__32
			{
			DebugLocation(1, 10);
			mT__32(); 

			}
			break;
		case 2:
			DebugEnterAlt(2);
			// Dsl.g:1:16: T__33
			{
			DebugLocation(1, 16);
			mT__33(); 

			}
			break;
		case 3:
			DebugEnterAlt(3);
			// Dsl.g:1:22: APOSTRAPHE
			{
			DebugLocation(1, 22);
			mAPOSTRAPHE(); 

			}
			break;
		case 4:
			DebugEnterAlt(4);
			// Dsl.g:1:33: STAR
			{
			DebugLocation(1, 33);
			mSTAR(); 

			}
			break;
		case 5:
			DebugEnterAlt(5);
			// Dsl.g:1:38: PLUS
			{
			DebugLocation(1, 38);
			mPLUS(); 

			}
			break;
		case 6:
			DebugEnterAlt(6);
			// Dsl.g:1:43: EQUAL
			{
			DebugLocation(1, 43);
			mEQUAL(); 

			}
			break;
		case 7:
			DebugEnterAlt(7);
			// Dsl.g:1:49: GREATER
			{
			DebugLocation(1, 49);
			mGREATER(); 

			}
			break;
		case 8:
			DebugEnterAlt(8);
			// Dsl.g:1:57: LESS
			{
			DebugLocation(1, 57);
			mLESS(); 

			}
			break;
		case 9:
			DebugEnterAlt(9);
			// Dsl.g:1:62: THAN
			{
			DebugLocation(1, 62);
			mTHAN(); 

			}
			break;
		case 10:
			DebugEnterAlt(10);
			// Dsl.g:1:67: NOT
			{
			DebugLocation(1, 67);
			mNOT(); 

			}
			break;
		case 11:
			DebugEnterAlt(11);
			// Dsl.g:1:71: IS
			{
			DebugLocation(1, 71);
			mIS(); 

			}
			break;
		case 12:
			DebugEnterAlt(12);
			// Dsl.g:1:74: WHEN
			{
			DebugLocation(1, 74);
			mWHEN(); 

			}
			break;
		case 13:
			DebugEnterAlt(13);
			// Dsl.g:1:79: VARIABLE
			{
			DebugLocation(1, 79);
			mVARIABLE(); 

			}
			break;
		case 14:
			DebugEnterAlt(14);
			// Dsl.g:1:88: NEWLINE
			{
			DebugLocation(1, 88);
			mNEWLINE(); 

			}
			break;
		case 15:
			DebugEnterAlt(15);
			// Dsl.g:1:96: STRING_LITERAL
			{
			DebugLocation(1, 96);
			mSTRING_LITERAL(); 

			}
			break;
		case 16:
			DebugEnterAlt(16);
			// Dsl.g:1:111: INT
			{
			DebugLocation(1, 111);
			mINT(); 

			}
			break;
		case 17:
			DebugEnterAlt(17);
			// Dsl.g:1:115: WS
			{
			DebugLocation(1, 115);
			mWS(); 

			}
			break;
		case 18:
			DebugEnterAlt(18);
			// Dsl.g:1:118: COMMENT
			{
			DebugLocation(1, 118);
			mCOMMENT(); 

			}
			break;
		case 19:
			DebugEnterAlt(19);
			// Dsl.g:1:126: LINE_COMMENT_SLASH
			{
			DebugLocation(1, 126);
			mLINE_COMMENT_SLASH(); 

			}
			break;

		}

	}


	#region DFA

	protected override void InitDFAs()
	{
		base.InitDFAs();
	}

	#endregion

}

} // namespace ParserTree.AntlrCode
